[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip rp235x"

[env]
DEFMT_LOG = "trace"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
debug = false
opt-level = 3