version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - ble-notifications
      - pico-2w-i2c-usb
      - pico-2w-ina228
      - read-usb
      - subscriber
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories:
      - /
    schedule:
      interval: "weekly"
