[package]
name = "event-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-sync = "0.7.2"
embassy-time = "0.5.0"
heapless = "0.9.1"
defmt = "1"
uuid = { version = "1.18.1", default-features = false }

[dev-dependencies]
futures = "0.3"
