[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
runner = "probe-rs run --protocol swd --chip nRF52840_xxAA"

[env]
DEFMT_LOG = "trace"

[profile.dev]
debug = true
# opt-level = 1

# [profile.release]
# debug = false
# opt-level = 3
